version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ".:/www"
            - .docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - dev-network

networks:
    dev-network:
        driver: bridge
